server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/huiseongshin/Project/BackEnd/msa-ecoomerce/git-local-repo
